name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --build-arg NUGET_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} --file dockerfile --tag Twitchbot.Services.Authentication:$(date +%s)
